### ISSUE TITLE
some more trees nodes are missing nodes to go with them

### ISSUE THREAD

**Issue by wsor4035** [minefaco/stripped_tree#11]
![image](https://user-images.githubusercontent.com/24964441/99861835-a1bad780-2b65-11eb-9c3c-e15a252c8bfa.png)

what the title says
node names: moretrees:date_palm_ffruit_trunk, moretrees:date_palm_mfruit_trunk, moretrees:palm_fruit_trunk, moretrees:rubber_tree_trunk_empty
do note and all but the last, they are fruit variants of the main node, so should probably produce the same stripped node

**Comment by minefaco** [comment]
i mean that's no necessary but whatever, i added the missing nodes.
